"""Deterministic template pipeline primitives."""

from .manifest import (
    TEMPLATE_OPERATIONAL_STATUSES,
    TEMPLATE_ORIGINS,
    TemplateManifest,
    TemplateSpec,
    load_manifest,
)
from .qc_policy import detect_qwen_fallback_scene_ids
from .learning_log import (
    ENTRY_ID_PATTERN,
    LEARNING_TYPES,
    REGRESSION_TEST_PATTERN,
    SEVERITIES,
    STATUSES,
    LearningDocument,
    LearningEntry,
    LearningLog,
    ensure_learning_markdown,
    parse_learning_markdown,
    render_learning_markdown,
    validate_learning_markdown,
)
from .renderer import (
    RenderDecision,
    TemplateRenderError,
    allow_qwen_fallback,
    build_render_decision,
    classify_render_exception,
    compositor_backend,
    production_template_mode,
    render_scene_to_image,
    scene_eligible_for_template,
    template_pipeline_mode,
    use_template_pipeline,
)
from .scene_schemas import (
    ALL_SCENE_TYPES,
    ATMOSPHERIC_SCENE_TYPES,
    DATA_SCENE_TYPES,
    LEGACY_ARCHETYPE_TO_SCENE_TYPE,
    SCHEMA_VERSION,
    SceneValidationError,
    normalize_scene_type,
    validate_scene,
    validate_scenes,
)
from .scene_typer import (
    SceneTyperError,
    SceneTyperProviderError,
    SceneTyperTimeoutError,
    SceneTyperValidationError,
    annotate_scenes_with_types,
)
from .selector import TemplateSelectionError, select_template

__all__ = [
    "ALL_SCENE_TYPES",
    "ATMOSPHERIC_SCENE_TYPES",
    "DATA_SCENE_TYPES",
    "LEGACY_ARCHETYPE_TO_SCENE_TYPE",
    "LEARNING_TYPES",
    "LearningDocument",
    "LearningEntry",
    "LearningLog",
    "REGRESSION_TEST_PATTERN",
    "TEMPLATE_OPERATIONAL_STATUSES",
    "TEMPLATE_ORIGINS",
    "SEVERITIES",
    "SCHEMA_VERSION",
    "SceneTyperError",
    "SceneTyperProviderError",
    "SceneTyperTimeoutError",
    "SceneTyperValidationError",
    "STATUSES",
    "RenderDecision",
    "SceneValidationError",
    "TemplateManifest",
    "TemplateRenderError",
    "TemplateSelectionError",
    "TemplateSpec",
    "allow_qwen_fallback",
    "annotate_scenes_with_types",
    "build_render_decision",
    "classify_render_exception",
    "compositor_backend",
    "detect_qwen_fallback_scene_ids",
    "ENTRY_ID_PATTERN",
    "ensure_learning_markdown",
    "load_manifest",
    "normalize_scene_type",
    "parse_learning_markdown",
    "production_template_mode",
    "render_learning_markdown",
    "render_scene_to_image",
    "scene_eligible_for_template",
    "select_template",
    "template_pipeline_mode",
    "use_template_pipeline",
    "validate_learning_markdown",
    "validate_scene",
    "validate_scenes",
]
